### ISSUE TITLE
Weird area of effect bug with Universal Remote.

### ISSUE THREAD

**Issue by Yabdat** [orbwoi/UniversalRemote#10]
Universal Remote  0.9.2
Tinkers Construct 2.7.3.30
Actually Additions r119

Using the remote removes the Area of effect mining with the tools form these mods.

Kind of hard to describe, watch this video:

https://www.youtube.com/watch?v=5ri-83DHmqY

Also some tools seems to do doubleclick after you have used the Universal Remote.

**Comment by orbwoi** [comment]
I tried to do what you do in the video but it works fine for me. I need a list of other mods you have installed- something else may be breaking it indirectly. Also, please send me your client logs.

**Comment by orbwoi** [comment]
Well shoot... the player proxy was leaking into the player interaction manager!
Fixed in 0.9.3

**Comment by Yabdat** [comment]
This is still happening in 0.9.3

Created a custom modpack with the Twitch launcher, with these mods:
Actually Additions 1.12.1-r19
JEI 1.12.1-4.7.8.95
Mantle 1.12-1.3.1.21
Tinkers Construct 1.12-2.7.3.30
Universal Remote 1.12-0.9.3

Basically the latest versions of all the mods.

Pastebin of console: https://pastebin.com/GGaMLH7a

**Comment by orbwoi** [comment]
How is that possible.. I tested carefully and it was definitely fixed.

*CHECKS*

OMG... I uploaded the wrong version of 0.9.3 which didn't actually have the fix in it.
This is why I shouldn't try to fix bugs when I'm in a hurry. :(

I'm so sorry. Thank you 10000% for finding this and re-reporting my bad upload!
Please try 0.9.4!
